### ISSUE TITLE
Disconnecting from websocket

### ISSUE THREAD

**Issue by gitagogaming** [Saamstep/discord-speak-detector-obs#1]
First time attempting to use this, got the bot to join voice channel as expected, and it does seem to trigger a 'hide source' but it then disconnects from websocket, then reconnects.. and continues to do so if i talk.. 
its never able to turn the source back on. 

Here is the error I was receiving in the logs. 

`0|speak-de | [Bot] Initalized

0|speak-detector  | TypeError: client.guilds.cache.get(...).catch is not a function
0|speak-detector  |     at Client.<anonymous> (C:\Users\dbcoo\Documents\GitHub\discord-speak-detector-obs\index.js:81:67)
0|speak-detector  |     at Client.emit (node:events:390:28)
0|speak-detector  |     at VoiceConnection.onSpeaking (C:\Users\dbcoo\Documents\GitHub\discord-speak-detector-obs\node_modules\discord.js\src\client\voice\VoiceConnection.js:516:21)
0|speak-detector  |     at PacketHandler.push (C:\Users\dbcoo\Documents\GitHub\discord-speak-detector-obs\node_modules\discord.js\src\client\voice\receiver\PacketHandler.js:114:23)
0|speak-detector  |     at Socket.<anonymous> (C:\Users\dbcoo\Documents\GitHub\discord-speak-detector-obs\node_modules\discord.js\src\client\voice\networking\VoiceUDPClient.js:131:76)
0|speak-detector  |     at Socket.emit (node:events:390:28)
0|speak-detector  |     at UDP.onMessage [as onmessage] (node:dgram:931:8)
0|speak-detector  | [OBS] Connected
0|speak-detector  | [Bot] Connected to VC 1
0|speak-detector  | [Bot] Initalized
0|speak-detector  | TypeError: client.guilds.cache.get(...).catch is not a function
0|speak-detector  |     at Client.<anonymous> (C:\Users\dbcoo\Documents\GitHub\discord-speak-detector-obs\index.js:81:67)
0|speak-detector  |     at Client.emit (node:events:390:28)
0|speak-detector  |     at VoiceConnection.onSpeaking (C:\Users\dbcoo\Documents\GitHub\discord-speak-detector-obs\node_modules\discord.js\src\client\voice\VoiceConnection.js:516:21)
0|speak-detector  |     at PacketHandler.push (C:\Users\dbcoo\Documents\GitHub\discord-speak-detector-obs\node_modules\discord.js\src\client\voice\receiver\PacketHandler.js:114:23)
0|speak-detector  |     at Socket.<anonymous> (C:\Users\dbcoo\Documents\GitHub\discord-speak-detector-obs\node_modules\discord.js\src\client\voice\networking\VoiceUDPClient.js:131:76)
0|speak-detector  |     at Socket.emit (node:events:390:28)
0|speak-detector  |     at UDP.onMessage [as onmessage] (node:dgram:931:8)
0|speak-detector  | [OBS] Connected
0|speak-detector  | [Bot] Connected to VC 1
0|speak-detector  | [Bot] Initalized
0|speak-detector  | TypeError: client.guilds.cache.get(...).catch is not a function
0|speak-detector  |     at Client.<anonymous> (C:\Users\dbcoo\Documents\GitHub\discord-speak-detector-obs\index.js:81:67)
0|speak-detector  |     at Client.emit (node:events:390:28)
0|speak-detector  |     at VoiceConnection.onSpeaking (C:\Users\dbcoo\Documents\GitHub\discord-speak-detector-obs\node_modules\discord.js\src\client\voice\VoiceConnection.js:516:21)
0|speak-detector  |     at PacketHandler.push (C:\Users\dbcoo\Documents\GitHub\discord-speak-detector-obs\node_modules\discord.js\src\client\voice\receiver\PacketHandler.js:114:23)
0|speak-detector  |     at Socket.<anonymous> (C:\Users\dbcoo\Documents\GitHub\discord-speak-detector-obs\node_modules\discord.js\src\client\voice\networking\VoiceUDPClient.js:131:76)
0|speak-detector  |     at Socket.emit (node:events:390:28)
0|speak-detector  |     at UDP.onMessage [as onmessage] (node:dgram:931:8)
0|speak-detector  | [OBS] Connected
0|speak-detector  | [Bot] Connected to VC 1
0|speak-detector  | [Bot] Initalized
`

**Comment by Saamstep** [comment]
hey there! the api might have changed something, i will see if i can reproduce the issue
